services:
  realtime-whisper:
    build:
      context: docker
      dockerfile: Dockerfile
      args:
        CUDA_ARCH: ${CUDA_ARCH:-75-real;86-real;89-real;90-real}
    image: whisper-realtime-trt:0.11.0
    volumes:
      - type: bind
        source: ./docker/scratch-space
        target: /root/scratch-space
    environment:
      VERBOSE: ${VERBOSE:-false}
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    entrypoint: ["/root/scratch-space/run-realtime-whisper.sh"]

